[project]
name = "agentic_terminal"
version = "0.1.0"
description = "an mcp which adds terminal capabilities to an agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.3",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
agentic_terminal = "agentic_terminal.main:main"